version: "3.9"

services:
  api-wrapper:
    build: ./service2
    container_name: api-wrapper
    environment:
      API_KEY: ${API_KEY}
      BASE_URL: ${BASE_URL}
      HF_HOME: /tmp/huggingface/
    networks:
      - vnet
    volumes:
      - ./service2/main.py:/app/main.py:Z
      - ./service2/security.py:/app/security.py:Z
      - ./service2/mcp_server.py:/app/mcp_server.py:Z
      - hf_cache_volume:/tmp/huggingface/
  
  service1:
    build: ./service1
    container_name: kali
    stdin_open: true
    tty: true
    networks: 
      - vnet
    volumes:
      - ./service1/app:/app:Z
    depends_on:
      api-wrapper

volumes:
  hf_cache_volume:
networks:
  vnet:
    name: vnet
    ipam:
      config:
        - subnet: 10.1.26.0/24
