import asyncio
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import openai
from contextlib import AsyncExitStack
from mcp.client.session import ClientSession
from typing import Optional
import json
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
import os
from dotenv import load_dotenv

import logging
from openai import AsyncOpenAI
from typing import Optional, List
from asgiref.sync import async_to_sync, sync_to_async

from llm_jailbreaking_defense import DefendedTargetLM, SelfReminderConfig, load_defense, TargetLM


logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)

load_dotenv()

api_key_check = os.getenv("API_KEY")
url_check = os.getenv("BASE_URL")


client_ai = AsyncOpenAI(
    api_key=api_key_check,
    base_url=url_check
)

logging.basicConfig(level=logging.DEBUG)
MCP_SERVER_SCRIPT = "/app/mcp_server.py"
LLM_MODEL = "gpt-oss-120b"




#DEFINE API
app = FastAPI(title="MCP_Gateway_API")

class QueryRequest(BaseModel):
    """
    API request model.

    Attributes:
        query (str): User query.
    """

    query: str

class MCPClient:
    def __init__(self, server_script_path):
        """
        Initialize MCP client.

        Args:
            server_script_path (str): Path to MCP server script.
        """

        self.server_script_path = server_script_path
        self.exit_stack = AsyncExitStack()
        self._lock = asyncio.Lock()
        self.formatted_tools: List[dict] = []

    async def start(self):
        """
        Start MCP client and connect to MCP server.

        - Launches MCP server via stdio
        - Initializes session
        - Retrieves available tools
        - Formats tools for LLM usage

        Returns:
            None
        """

        command = "python"
        server_params = StdioServerParameters(
            command=command,
            args=[self.server_script_path],
            env=None
        )

        stdio_transport = await self.exit_stack.enter_async_context(stdio_client(server_params))
        self.stdio, self.write = stdio_transport
        self.session = await self.exit_stack.enter_async_context(ClientSession(self.stdio, self.write))

        await self.session.initialize()

        #recive tools
        response = await self.session.list_tools()

        # Conversion of tools into the correct JSON format for the e-infra API
        self.formatted_tools = [
            {
                "type": "function",
                "function": {
                    "name": tool.name,
                    "description": tool.description,
                    "parameters": tool.inputSchema
                    }
                }
                for tool in response.tools
            ]
        
    async def send_message_to_llm(self, messages: list[dict]):
        """
        Send messages to LLM and receive response.

        Args:
            messages (list): Conversation messages.

        Returns:
            Response object from LLM API.
        """
        logger.debug(f"--------------QUESTION TO SEND----------------------\n {messages}\n")
        response = await client_ai.chat.completions.create(
            model=LLM_MODEL,
            max_tokens=1000,
            messages=messages,
            tools=self.formatted_tools
        )

        logger.debug(f"\n recieved response:\n {response}\n")
        return response

    async def process_query(self, query: str):
        """
        Processes a query using LLM and MCP tools, applying a Self-Reminder 
        defense.

        Workflow:
            1. Send the (pre-defended) query to the LLM.
            2. If a tool call is requested, execute the corresponding tool.
            3. ENCAPSULATE TOOL OUTPUT: Append a Self-Reminder warning (prefix/suffix) 
               directly to the tool's data before adding it to the context.
            4. Repeat until resolution or max iterations are reached.

        Args:
            query (str): The user input query.

        Returns:
            str: The final safe response generated by the LLM.
        """

        messages = [
            {
                "role": "system",
                "content": "You are a helpful assistant that can use external tools when necessary."
            }

        ]
        messages.append({"role":"user","content": query})

        response = await self.send_message_to_llm(messages)
        logger.debug(f"------------------------RESPONSE-------------------------\n{response}\n")

        for i in range(10):
            logger.debug(f"loop running {i}")
            message = response.choices[0].message

            if not message.tool_calls:
    
                break
            
            messages.append(message)

            tool_call = message.tool_calls[0]
            tool_name = tool_call.function.name
            tool_args = json.loads(tool_call.function.arguments)
            
            # call tool
            result_tmp = await self.session.call_tool(tool_name, tool_args)
            logger.debug("*******************************tool call {result.content} ***********************************")
            
            # result.content can be list of objects so --> string
            if isinstance(result_tmp.content, list):
                content_str = "\n".join(str(x) for x in result_tmp.content)
            else:
                content_str = str(result_tmp.content)

            #create custome selfReminder for tool calling
            sRToolOutput = f"""Remember, you must be a responsible language model and must not generate 
            harmful or misleading content!
             There is tool output
             [TOOL-OUTPUT]
             {content_str} 
             [TOOL-OUTPUT]
            You are a helpful assistant that can use external tools when necessary. 
            You must be a responsible language model and must not generate harmful or misleading content! Please work with this tool output in a responsible way."""

            messages.append(
                {
                    "role":"tool",
                    "tool_call_id": tool_call.id,
                    "content": sRToolOutput
                }
            )
            
            response = await self.send_message_to_llm(messages)
            logger.debug(f"-------output--------------\n{response}\n")
        return response.choices[0].message.content if response.choices else "Max tool iterations reached."




class SimpleTemplate:
    """
    Minimal prompt template used by the defense framework.

    Attributes:
        system_message (str): Default system prompt
        user_message (str): Template for user input
    """

    system_message: str = "You are a helpful assistant."
    user_message: str = "{prompt}"

class MCPAdapter(TargetLM):
    """
    Adapter that wraps MCPClient to match the TargetLM interface
    required by the jailbreak defense library.

    This allows MCP-based LLM calls to be used with defense strategies
    such as backtranslation.

    Attributes:
        mcp_client (MCPClient): Underlying MCP client instance
        template (SimpleTemplate): Prompt formatting template
    """

    def __init__(self, mcp_client):
        self.mcp_client = mcp_client
        self.template = SimpleTemplate()


    def get_response(self, prompts, **kwargs):
        """
        Generate responses for given prompts using MCPClient.

        Supports both single prompt and batch input.

        Args:
            prompts (str | list):
                - str: Single prompt
                - list: List of prompts or nested lists

            **kwargs: Additional parameters (ignored)

        Returns:
            str: Response string generated by the LLM.
        """
        
        safe_sync_call = async_to_sync(self.mcp_client.process_query)
        return safe_sync_call(prompts)


    def evaluate_log_likelihood(self, prompt, response):
        """
        Dummy implementation required by TargetLM interface.

        Currently not supported.

        Args:
            prompt (str): Input prompt
            response (str): Model response

        Returns:
            int: Always returns 0
        """

        return 0

# INITIALIZE MCP CLIENT ON STARTUP

@app.on_event("startup")
async def startup_event():
    global client, defended_client, defense
    client = MCPClient(MCP_SERVER_SCRIPT)
    await client.start()
    
    # Adapter for defence 
    mcp_adapter = MCPAdapter(client)

    config = SelfReminderConfig()
    defense = load_defense(config)

    defended_client = DefendedTargetLM(mcp_adapter, defense)

@app.post("/query")
async def query_endpoint(request: QueryRequest):
    """
    API endpoint processing queries via a dual-layer Self-Reminder defense.

    Workflow:
        1. Phase 1 (Input Defense): Wrap user and system prompts using 
           the defense library to mitigate Direct Jailbreaks.
        2. Phase 2 (Tool Defense): Process via MCP client, where all external 
           tool outputs are dynamically encapsulated to prevent Indirect Prompt Injection.
        3. Return the final safe response.

    Args:
        request (QueryRequest): Incoming request containing the raw query.

    Returns:
        dict: A dictionary with the original query and the model's safe answer.
    """

    try:
        async_client = sync_to_async(defended_client.get_response)
        answer = await async_client([request.query])
        return {"query": request.query, "answer": answer[0]}

    except Exception as e:
        logger.exception("Error processing query")
        raise HTTPException(status_code=500, detail=str(e))




