from llm_client import MCPClient
import asyncio
import argparse 
import os 
os.environ["CUDA_VISIBLE_DEVICES"]="1" 
import sys 
sys.path.append('./utils') 
from utils import * 
import numpy as np 
from mask_utils import * 
from augmentations import * 
import spacy 
from similarity import *
from help_method import change_prompt
import logging

metric = spacy.load("en_core_web_md")

logger = logging.getLogger(__name__) 
logging.basicConfig(level=logging.DEBUG) 

def update_divergence(output_list, simialrity_eval='spacy', metric=None, top_string=None): 
    """
    Calculate the maximum semantic divergence among a list of LLM responses.

    Workflow:
        1. Check if any of the outputs indicate a blocked/refused response.
        2. Optionally truncate the strings to a specified length (`top_string`).
        3. Compute a pairwise similarity matrix using the chosen NLP model (Spacy/Transformer).
        4. Clip similarity values (min 0.01) to avoid mathematical instability (e.g., division by zero).
        5. Calculate the divergence matrix based on the similarities.
        6. Clip the final divergence values to a maximum of 100 to prevent infinite extremes.
        7. Return the highest divergence found, along with the block status.

    Args:
        output_list (List[str]): The list of text responses generated by the LLM.
        simialrity_eval (str, optional): The method used for similarity evaluation ('spacy' or 'transformer'). Defaults to 'spacy'.
        metric (Any, optional): The loaded NLP model (e.g., Spacy language model) used for evaluation. Defaults to None.
        top_string (int, optional): The maximum number of characters to evaluate from each string. Defaults to None.

    Returns:
        Tuple[float, bool]: 
            - max_div (float): The maximum calculated divergence score.
            - all_block (bool): True if the outputs indicate the LLM refused to answer, False otherwise.
    """

    all_block = determine_blocked(output_list) 
    number = len(output_list) 
    similarity_matrix = np.zeros((number, number)) 
    divergence_matrix = np.zeros((number, number)) 
    if top_string != None: 
        output_list = [_str[:top_string] for _str in output_list] 
    if simialrity_eval in ['spacy', 'transformer']: 
        for i in range(number): 
            for j in range(number): 
                similarity_matrix[i,j] = get_similarity(output_list[i], output_list[j], method=simialrity_eval, misc=metric)
    else: 
        print('not a valid similarity metric') 
        
    similarity_matrix = np.clip(similarity_matrix, 0.01, None) 

    for i in range(number): 
        for j in range(number): 
            if i != j: 
                divergence_matrix[i, j] = get_divergence(similarity_matrix, i, j) 

    divergence_matrix = np.clip(divergence_matrix, None, 100) 
    return divergence_matrix.max(), all_block 
    

async def jailGuard(prompt: str, client):
    """
    Evaluate if an input prompt is a jailbreak or injection attack using semantic divergence.

    Workflow:
        1. Generate multiple augmented variants of the original user prompt.
        2. Execute parallel asynchronous LLM queries for all variants using the MCP client.
        3. Collect and handle the results, ensuring network/API exceptions do not crash the process.
        4. Calculate the semantic divergence between the collected responses.
        5. Compare the maximum divergence against a predefined threshold (0.3).
        6. Return True (attack detected) if the responses diverge significantly, or False (benign) if they are consistent.

    Args:
        prompt (str): The original user input query to be evaluated.
        client (Any): The initialized MCPClient instance used to communicate with the LLM.

    Returns:
        bool: True if the prompt is classified as an attack, False otherwise.
    """

    generated_variants = []
    responses = []

    for _ in range(4):
        variant = change_prompt(prompt)
        generated_variants.append(variant)

    tasks = []
    for variant in generated_variants:
        prompt_text = variant[0] if isinstance(variant, list) else variant
        
        tasks.append(client.process_query(prompt_text))

    results = await asyncio.gather(*tasks, return_exceptions=True)

    for result in results:
    
        if isinstance(result, Exception):
            responses.append("No response!")
            logging.debug(f"\nERROR ON RESULT {result}\n")
        else:
            
            logging.debug(f"RESPONSE JAIGUARD----------------------\n{result}\n")
        
            responses.append(result or "")

    max_div, jailbreak_keywords = update_divergence(
        output_list=responses,
        metric=metric
    )

    threshold = 0.3
    detect_value = detect_attack(max_div, jailbreak_keywords, threshold)
    logging.debug(f"JAILGUARD RESPONSEEEEEEEEEEEEEEEEEEEEEEEEEE\n{detect_value}\n")

    return detect_value
